server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

#spring:
#  security:
#    oauth2:
#      authorization server:
#        client:
#          public-client:
#            registration:
#              client-id: "public-client"
#              client-authentication-methods:
#                - "none"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://127.0.0.1:4200"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true
#            require-proof-key: true
